/**
 * Daily refresh of metal "Pengar direkt" prices from Kaplans + EUR cross
 * rates from frankfurter.app. Regenerates lib/daily-rates.ts in place.
 *
 * Invoked by .github/workflows/daily-rates.yml.
 *
 * Usage:
 *   pnpm exec tsx scraper/sync-rates.ts
 *
 * Output:
 *   - Overwrites lib/daily-rates.ts with today's values.
 *   - Exits 0 even when one of the sources is offline (we keep yesterday's
 *     numbers rather than zeroing them out). Exits 1 only on a parse/
 *     unexpected error.
 */

import { readFileSync, writeFileSync } from "node:fs";

const KAPLANS_URL = "https://www.kaplansadelmetall.se/guldpriser/dagspris";
const FRANKFURTER_URL = "https://api.frankfurter.app/latest?from=EUR&to=USD,SEK,GBP,NOK,DKK";
const TARGET_PATH = "lib/daily-rates.ts";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36";

interface Rates {
  goldSekPerG: Record<string, number>;
  silverSekPerG: Record<number, number>;
  eurPer: Record<string, number>;
}

// ── parsing helpers ───────────────────────────────────────────────────────

/** Strip all HTML tags and collapse whitespace. */
function stripTags(html: string): string {
  return html.replace(/<[^>]+>/g, "|").replace(/\s+/g, " ").replace(/\|+/g, "|");
}

function parseSv(num: string): number {
  // "1 172,65" → 1172.65
  return Number(num.replace(/\s/g, "").replace(",", "."));
}

/**
 * Pull "Pengar direkt" SEK/g for each gold karat from the kaplans HTML.
 * Each row: |Renhet| Pengar | Presentkort | London Fix |
 * We take the first numeric column.
 */
function parseKaplans(html: string): { gold: Record<string, number>; silver: Record<number, number> } {
  const tables = html.match(/<table[^>]*>[\s\S]*?<\/table>/g) ?? [];
  if (tables.length < 2) {
    throw new Error(`Kaplans: expected ≥2 tables, found ${tables.length}`);
  }

  const gold: Record<string, number> = {};
  const silver: Record<number, number> = {};

  // Gold table is index 0, silver is index 1 (verified 2026-05-02).
  const goldText = stripTags(tables[0]);
  for (const m of goldText.matchAll(/Guld(?:tacka)?\s*(\d{1,2}(?:[.,]\d)?)\s*K[^\d]*?(\d[\d ]*[.,]?\d*)/g)) {
    const karat = m[1].replace(",", ".");
    gold[karat] = parseSv(m[2]);
  }
  // Mirror 21.6K to 22K and 21K so titles using either match.
  if (gold["21.6"]) {
    gold["21"] = gold["21.6"];
    gold["22"] = gold["21.6"];
  }

  const silverText = stripTags(tables[1]);
  for (const m of silverText.matchAll(/Silver(?:mynt)?\s*(\d{3})[^\d]*?(\d+[.,]?\d*)/g)) {
    silver[parseInt(m[1], 10)] = parseSv(m[2]);
  }

  if (Object.keys(gold).length < 4) throw new Error("Kaplans: parsed too few gold rows");
  if (Object.keys(silver).length < 4) throw new Error("Kaplans: parsed too few silver rows");
  return { gold, silver };
}

// ── fetchers ──────────────────────────────────────────────────────────────

async function fetchKaplans() {
  const res = await fetch(KAPLANS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Kaplans HTTP ${res.status}`);
  return parseKaplans(await res.text());
}

async function fetchFx(): Promise<Record<string, number>> {
  // Frankfurter returns "rates": { USD: 1.07, SEK: 11.4, ... } where each
  // value is units of that currency per 1 EUR. We invert to "EUR per X".
  const res = await fetch(FRANKFURTER_URL);
  if (!res.ok) throw new Error(`Frankfurter HTTP ${res.status}`);
  const data = (await res.json()) as { rates: Record<string, number> };
  const eurPer: Record<string, number> = { EUR: 1 };
  for (const [ccy, perEur] of Object.entries(data.rates)) {
    eurPer[ccy] = 1 / perEur;
  }
  return eurPer;
}

// ── output ────────────────────────────────────────────────────────────────

function renderFile(rates: Rates, fetchedAt: string): string {
  const fmt = (n: number) => Number(n.toFixed(4)).toString();
  const sortedGoldKarats = Object.keys(rates.goldSekPerG).sort((a, b) => Number(b) - Number(a));
  const sortedSilverPurities = Object.keys(rates.silverSekPerG).map(Number).sort((a, b) => b - a);

  return `/**
 * Daily metal-spot prices + FX rates.
 *
 * AUTO-GENERATED by scraper/sync-rates.ts (daily 06:00 UTC via the
 * \`daily-rates.yml\` GitHub Actions workflow). Do not edit by hand —
 * any manual changes here will be clobbered on the next workflow run.
 *
 * Sources:
 *   - Yellow gold + silver: https://www.kaplansadelmetall.se/guldpriser/dagspris
 *     "Pengar direkt" column = the rate Kaplans pays out same-day
 *   - FX: https://api.frankfurter.app  (ECB reference rates)
 *
 * White gold and rose gold are NOT auto-updated — kaplans doesn't list
 * them, so they stay in lib/jewellery-value.ts as static defaults.
 */

export const FETCHED_AT = ${JSON.stringify(fetchedAt)};

/** Gold "Pengar direkt" SEK/g, by karat string. */
export const GOLD_SEK_PER_G: Record<string, number> = {
${sortedGoldKarats.map((k) => `  ${JSON.stringify(k).padEnd(7)}: ${fmt(rates.goldSekPerG[k])},`).join("\n")}
};

/** Silver "Pengar direkt" SEK/g, by purity number. */
export const SILVER_SEK_PER_G: Record<number, number> = {
${sortedSilverPurities.map((p) => `  ${p}: ${fmt(rates.silverSekPerG[p])},`).join("\n")}
};

/** EUR per 1 unit of the named currency. ECB reference rates. */
export const EUR_PER: Record<string, number> = {
${Object.keys(rates.eurPer).sort().map((c) => `  ${c}: ${fmt(rates.eurPer[c])},`).join("\n")}
};
`;
}

async function main() {
  console.log("[sync-rates] start", new Date().toISOString());

  // Always start from the file currently committed to disk so a partial
  // failure (one upstream offline) keeps yesterday's numbers for the rest.
  const existing = readFileSync(TARGET_PATH, "utf8");
  const goldFromFile = extractRecord(existing, "GOLD_SEK_PER_G");
  const silverFromFile = extractRecordNum(existing, "SILVER_SEK_PER_G");
  const fxFromFile = extractRecord(existing, "EUR_PER");

  let gold: Record<string, number> = goldFromFile;
  let silver: Record<number, number> = silverFromFile;
  let eurPer: Record<string, number> = fxFromFile;

  try {
    const k = await fetchKaplans();
    gold = k.gold;
    silver = k.silver;
    console.log("[sync-rates] kaplans ok:", Object.keys(gold).length, "gold rows,", Object.keys(silver).length, "silver");
  } catch (e) {
    console.error("[sync-rates] kaplans failed, keeping yesterday's metal prices:", (e as Error).message);
  }

  try {
    eurPer = await fetchFx();
    console.log("[sync-rates] fx ok:", Object.keys(eurPer).length, "currencies");
  } catch (e) {
    console.error("[sync-rates] fx failed, keeping yesterday's rates:", (e as Error).message);
  }

  const rates: Rates = { goldSekPerG: gold, silverSekPerG: silver, eurPer };
  const fetchedAt = new Date().toISOString();
  writeFileSync(TARGET_PATH, renderFile(rates, fetchedAt));
  console.log("[sync-rates] wrote", TARGET_PATH, "@", fetchedAt);
}

// Read a "Record<string, number> = { ... }" block out of the existing file.
function extractRecord(src: string, name: string): Record<string, number> {
  const re = new RegExp(`export\\s+const\\s+${name}\\s*:\\s*[^=]*=\\s*\\{([\\s\\S]*?)\\};`);
  const m = src.match(re);
  const out: Record<string, number> = {};
  if (!m) return out;
  for (const row of m[1].matchAll(/"([^"]+)"\s*:\s*([\d.]+)/g)) {
    out[row[1]] = Number(row[2]);
  }
  return out;
}
// Same but for numeric keys.
function extractRecordNum(src: string, name: string): Record<number, number> {
  const re = new RegExp(`export\\s+const\\s+${name}\\s*:\\s*[^=]*=\\s*\\{([\\s\\S]*?)\\};`);
  const m = src.match(re);
  const out: Record<number, number> = {};
  if (!m) return out;
  for (const row of m[1].matchAll(/(\d+)\s*:\s*([\d.]+)/g)) {
    out[Number(row[1])] = Number(row[2]);
  }
  return out;
}

main().catch((err) => {
  console.error("[sync-rates] fatal:", err);
  process.exit(1);
});
