/**
 * Daily metal-spot prices + FX rates.
 *
 * AUTO-GENERATED by scraper/sync-rates.ts (daily 06:00 UTC via the
 * `daily-rates.yml` GitHub Actions workflow). Do not edit by hand —
 * any manual changes here will be clobbered on the next workflow run.
 *
 * Sources:
 *   - Yellow gold + silver: https://www.kaplansadelmetall.se/guldpriser/dagspris
 *     "Pengar direkt" column = the rate Kaplans pays out same-day
 *   - FX: https://api.frankfurter.app  (ECB reference rates)
 *
 * White gold and rose gold are NOT auto-updated — kaplans doesn't list
 * them, so they stay in lib/jewellery-value.ts as static defaults.
 */

export const FETCHED_AT = "2026-07-01T09:51:04.270Z";

/** Gold "Pengar direkt" SEK/g, by karat string. */
export const GOLD_SEK_PER_G: Record<string, number> = {
  "24"   : 1180.18,
  "23"   : 1023.86,
  "22"   : 961.54,
  "21.6" : 961.54,
  "21"   : 961.54,
  "18"   : 801.28,
  "14"   : 623.22,
  "9"    : 400.64,
};

/** Silver "Pengar direkt" SEK/g, by purity number. */
export const SILVER_SEK_PER_G: Record<number, number> = {
  925: 10.82,
  900: 10.53,
  830: 9.71,
  800: 9.36,
  600: 7.02,
  400: 4.68,
};

/** EUR per 1 unit of the named currency. ECB reference rates. */
export const EUR_PER: Record<string, number> = {
  DKK: 0.1338,
  EUR: 1,
  GBP: 1.1604,
  NOK: 0.0884,
  SEK: 0.0901,
  USD: 0.8777,
};
