/**
 * Daily metal-spot prices + FX rates.
 *
 * AUTO-GENERATED by scraper/sync-rates.ts (daily 06:00 UTC via the
 * `daily-rates.yml` GitHub Actions workflow). Do not edit by hand —
 * any manual changes here will be clobbered on the next workflow run.
 *
 * Sources:
 *   - Yellow gold + silver: https://www.kaplansadelmetall.se/guldpriser/dagspris
 *     "Pengar direkt" column = the rate Kaplans pays out same-day
 *   - FX: https://api.frankfurter.app  (ECB reference rates)
 *
 * White gold and rose gold are NOT auto-updated — kaplans doesn't list
 * them, so they stay in lib/jewellery-value.ts as static defaults.
 */

export const FETCHED_AT = "2026-09-14T12:05:29.785Z";

/** Gold "Pengar direkt" SEK/g, by karat string. */
export const GOLD_SEK_PER_G: Record<string, number> = {
  "24"   : 1285.22,
  "23"   : 1114.98,
  "22"   : 1047.11,
  "21.6" : 1047.11,
  "21"   : 1047.11,
  "18"   : 872.59,
  "14"   : 678.68,
  "9"    : 436.3,
};

/** Silver "Pengar direkt" SEK/g, by purity number. */
export const SILVER_SEK_PER_G: Record<number, number> = {
  925: 11.96,
  900: 11.64,
  830: 10.74,
  800: 10.35,
  600: 7.76,
  400: 5.17,
};

/** EUR per 1 unit of the named currency. ECB reference rates. */
export const EUR_PER: Record<string, number> = {
  DKK: 0.1338,
  EUR: 1,
  GBP: 1.1653,
  NOK: 0.0928,
  SEK: 0.089,
  USD: 0.8627,
};
