/**
 * Daily metal-spot prices + FX rates.
 *
 * AUTO-GENERATED by scraper/sync-rates.ts (daily 06:00 UTC via the
 * `daily-rates.yml` GitHub Actions workflow). Do not edit by hand —
 * any manual changes here will be clobbered on the next workflow run.
 *
 * Sources:
 *   - Yellow gold + silver: https://www.kaplansadelmetall.se/guldpriser/dagspris
 *     "Pengar direkt" column = the rate Kaplans pays out same-day
 *   - FX: https://api.frankfurter.app  (ECB reference rates)
 *
 * White gold and rose gold are NOT auto-updated — kaplans doesn't list
 * them, so they stay in lib/jewellery-value.ts as static defaults.
 */

export const FETCHED_AT = "2026-07-20T09:16:42.787Z";

/** Gold "Pengar direkt" SEK/g, by karat string. */
export const GOLD_SEK_PER_G: Record<string, number> = {
  "24"   : 1180.13,
  "23"   : 1023.81,
  "22"   : 961.49,
  "21.6" : 961.49,
  "21"   : 961.49,
  "18"   : 801.24,
  "14"   : 623.19,
  "9"    : 400.62,
};

/** Silver "Pengar direkt" SEK/g, by purity number. */
export const SILVER_SEK_PER_G: Record<number, number> = {
  925: 10.53,
  900: 10.24,
  830: 9.45,
  800: 9.11,
  600: 6.83,
  400: 4.55,
};

/** EUR per 1 unit of the named currency. ECB reference rates. */
export const EUR_PER: Record<string, number> = {
  DKK: 0.1338,
  EUR: 1,
  GBP: 1.1751,
  NOK: 0.0906,
  SEK: 0.0906,
  USD: 0.8745,
};
